### PR TITLE
adds sepolia USDT and USDC

### PR DESCRIPTION
**Pull request by sneg55**

### CODE REVIEW

**Comment by smol-ninja** [comment]
Looks good to me. Just a smol feedback that we prefer using present tense for PR titles and commit messages. The objective is to tell what the commit would do rather than what you did.

**Comment by razgraf** [comment]
Thank you for the PR @sneg55!

Some items which I've addressed in a commit:
- addresses should be checksummed (you can use @PaulRBerg's [ethsum web tool ](https://ethsum.netlify.app/) to do that on the fly)
- (optional) we have a repository where we upload token icons (https://github.com/sablier-labs/sablier-labs.github.io exposed under `files.sablier.io/...`). There's no problem in using icons off the web, but using our own makes sure we're not rate-limited or the icon doesn't disappear one day + we control the icon's quality

**Comment by PaulRBerg** [comment]
Are these the officially endorsed USDT and USDC on Sepolia?

**Comment by sneg55** [comment]
> Are these the officially endorsed USDT and USDC on Sepolia?

I didn't research it that much, but both are available through Aave Sepolia Faucet: https://staging.aave.com/faucet/, so it must be it.

**Comment by razgraf** [comment]
Looks like they are: [USDC](https://developers.circle.com/stablecoins/docs/usdc-on-test-networks), [USDT](https://staging.aave.com/reserve-overview/?underlyingAsset=0xaa8e23fb1079ea71e0a56f48a2aa51851d8433d0&marketName=proto_sepolia_v3) (from aave)

**Pull request merged**
